//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repPruebaMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tabla
    {
        public int idPro { get; set; }
        public string sku { get; set; }
        public string nombre { get; set; }
        public double precio { get; set; }
    }
}
